### ISSUE TITLE
"quit" command doesn't handle alerts as raised by "onbeforeunload" event listeners

### ISSUE THREAD

**Issue by dewanprakash** [mozilla/geckodriver#1151]
## System
* Version: 0.19.1
* Platform: Windows 7 Pro
* Firefox: 57.0.1
* Selenium: java + 3.8.1

## Testcase

driver.quit() when called in a situation, where the application under test have unsaved changes - Firefox presents with the dialog to Leave/Stay on the page with unsaved changes. This halts the execution forever. The same gets gracefully cleaned up with chromedriver, i.e. browser close + chromedriver cleanup. 

driver.quit() in normal scenarios works fine with Firefox as well.
![firefox closure](https://user-images.githubusercontent.com/22215348/35606038-f0772a92-0672-11e8-9f72-4e617ea796f1.png)

**Comment by soumyababy81** [comment]
Use driver.close() before driver.quit(). driver.close() deletes the session without checking for the unsaved changes.

**Comment by dewanprakash** [comment]
thanks for the response @soumyababy81 - however with that, i.e. driver.close() taking away the driver handle driver.quit() will throw exception, which one would have to catch and suppress.

**Comment by whimboo** [comment]
Thank you for filing this issue. I field https://bugzilla.mozilla.org/show_bug.cgi?id=1434872 to get this fixed for `quit`.

**Comment by DavidGWheeler** [comment]
The suggested work-around of using driver.close() does NOT work.  The result is the same as using driver.quit(), the test hangs and Firefox does not close.

**Comment by whimboo** [comment]
The only workaround right now which I would see is to navigate away from such a web page before quitting the driver. That should also remove the alert.

**Comment by whimboo** [comment]
This was already fixed a long time ago for Firefox 61. Sorry, that I missed to update this issue.

**Comment by zeit200** [comment]
@whimboo, hi, it is still reproducible on 0.24.0 with firefox 65.0 if you enable beforeunload event - dom.disable_beforeunload = false
