### ISSUE TITLE
Upload Files one by one

### ISSUE THREAD

**Issue by morndiaye** [mozilla/geckodriver#1214]
## System

* Version: geckodriver 0.20.0 
* Platform: Linux Ubuntu 16.04 LTSfirefo 
* Firefox: 58.0.2 (64bit)
* Selenium:  3.10.0 

## Testcase
save file test:  UploadFiles.robot

*** Settings ***
Library  Selenium2Library
Test Setup  Open test browser
Test Teardown  Close test browser

*** Variables ***
${URL}      https://encodable.com/uploaddemo/

*** Test Cases ***

Upload Files
	Set Selenium Speed    1 seconds
	Go to  https://encodable.com/uploaddemo/
	Page should contain     FileChucker
	Choose File                                 id=uploadname1    ${CURDIR}/Selenium.jpg
	Capture Page Screenshot
	Choose File                                 id=uploadname1    ${CURDIR}/Selenium2.jpg
	Capture Page Screenshot
	Choose File                                 id=uploadname1    ${CURDIR}/Selenium3.jpg
	Capture Page Screenshot

*** Keywords ***

Open test browser
	Set Selenium Speed    1 seconds
	Open Browser  ${URL}  ${BROWSER}

Close test browser
	Close all browsers

## Run Test
pybot --variable BROWSER:firefox --variable VERSION:latest --variable PLATFORM:LINUX UploadFiles.robot

## Comments:
Hi !
I am trying to  upload images (Selenium.jpg, Selenium2.jpg and Selenium3.jpg respectively)  using Selenium3.
However, when I use geckodriver+firefox:
- The first upload file (Selenium.jpg) is ok
- The second upload (Selenium1.jpg) is ko 
It takes multiple files (Selenium.jpg+selenium1.jpg) Instead of taking  selenium1.jpg
- The third upload (Selenium2.jpg) is also ko 
It takes multiple files (Selenium.jpg+selenium1.jpg+selenium2.jpg) Instead of taking  selenium2.jpg
...

Using chromedriver+chome work fine

## Trace-level log

[test_upload_file.tar.gz](https://github.com/mozilla/geckodriver/files/1806605/test_upload_file.tar.gz)

**Comment by whimboo** [comment]
@morndiaye the attached log is not a trace log. Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to create one. Also better attach them as file instead of pasting into a comment. Thanks.

**Comment by morndiaye** [comment]
Hello @whimboo  please find the attached log with log_level=TRACE
Hope it's the log you need.
Thanks
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1830109/geckodriver.log)

**Comment by whimboo** [comment]
Thank you for the log. Inspecting it I found a possible bug in Marionette. It's filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1448792 now.

**Comment by andreastt** [comment]
This is intentional behaviour according to the WebDriver specification. See the definition of [Element Send Keys](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-send-keys) substep 10.

**Comment by whimboo** [comment]
Lets move further discussion to the filed bug report. We will update this issue once it has been clarified.

**Comment by whimboo** [comment]
This is fixed in Firefox Nightly 62.0a1 now.

**Comment by morndiaye** [comment]
Hello,
I have updated the version of firefox from 58.0.2 to 66.0.2 and geckodriver from 0.24.0  to test this fix, but I still have the same problem that I described  in my first comment.
You can find the attached log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/3074405/geckodriver.log)

**Comment by whimboo** [comment]
Per the WebDriver specification this endpoint will not support sending multiple files one after the other to the file input element. You will have to send them all at once as a text separated by a `\n`. 

For your purpose you will have to wait until https://github.com/w3c/webdriver/issues/1355 has been implemented in the drivers.
