### ISSUE TITLE
/moz/addon/install command regression: "data did not match any variant of untagged enum Helper"

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#1383]
## System

* Version: 0.22
* Platform: Windows
* Firefox: Nightly 64.0a1 (2018-09-20) (64-bit)
* Selenium: HEAD

## Trace-level log

0.22 trace log:

```
1537532269894	webdriver::server	DEBUG	-> POST /session/ff9a2565-6cd5-4442-b86d-0bdc3c0ac9dd/moz/addon/install {
  "path": "c:\\Temp\\search_encrypt-2.8.3-an+fx.xpi"
}
1537532269895	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"data did not match any variant of untagged enum Helper","stacktrace":""}}
```

0.21 trace log:

```
1537527046406	webdriver::server	DEBUG	-> POST /session/3f70bc2e-cde0-4326-bee8-310df0708a95/moz/addon/install {
  "path": "c:\\Temp\\search_encrypt-2.8.3-an+fx.xpi"
}
1537527047014	Marionette	TRACE	0 -> [0,2,"Addon:Install",{"path":"c:\\Temp\\search_encrypt-2.8.3-an+fx.xpi","temporary":false}]
1537527052973	Marionette	TRACE	0 <- [1,2,null,{"value":"@searchencrypt"}]
1537527052974	webdriver::server	DEBUG	<- 200 OK {"value":"@searchencrypt"}
```

**Comment by andreastt** [comment]
I suppose we don’t use this endpoint in our internal infrastructure, as the test harnesses who need to install web extensions speak to Marionette directly. It’s unfortunate that we’e not dogfooding this endpoint, as we likely would have caught this regression.

@whimboo Can you look at this? I guess maybe one of the parameters is not optional or something?

**Comment by whimboo** [comment]
It's a regression with the Serde changes, and I ask @barancev to file a bug. He is also going to do that soon. Please let us know here once it has been done. Thanks.

**Comment by barancev** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1493149

**Comment by whimboo** [comment]
This is fixed and will be part of the next release of geckodriver.

**Comment by speedplane** [comment]
I am still seeing this same error using Firefox 63.0.3 and geckodriver 0.23.0

**Comment by speedplane** [comment]
For folks coming using Selenium and running into the issue, you can work around it by adding the `temporary` parameter, e.g.,:

`driver.install_addon(addon_path, temporary=True)`

**Comment by andreastt** [comment]
@speedplane Can you file a new bug and attach a trace-log?

**Comment by whimboo** [comment]
@speedplane are you sure that you are using geckodriver 0.23.0? I doubt that given that we have a unit test which exactly tests this: https://hg.mozilla.org/releases/mozilla-beta/rev/a887958ca099#l1.60
