### ISSUE TITLE
action.scrollDown(element, xOffset); doesn't work in geckodriver

### ISSUE THREAD

**Issue by tomaszwojciechowski** [mozilla/geckodriver#1471]
## System

* Version: 0.23.0
* Platform: Windows 10
* Firefox: 64.0
* Selenium: 3.141.59

## Testcase
Following method doesn't work:

    public void scrollDown(WebElement element, int xOffset) {
        action = new Action(this.driver);
        action.scrollDown(element, xOffset);
    }

**Comment by andreastt** [comment]
The WebDriver WG resolved at the F2F in Lyon last year to add a scroll into view primitive for the actions API, but it has not yet been specified or implemented.

See https://www.w3.org/2018/10/26-webdriver-minutes.html#item02 and https://github.com/w3c/webdriver/issues/1005.

**Comment by kretschmannj** [comment]
@andreastt  Any updates on this?  It's still an issue with the latest geckodriver version.

**Comment by whimboo** [comment]
We are waiting for the Webdriver specification to be updated.
