### ISSUE TITLE
Wait for element to become stale throws "NoSuchElementException"

### ISSUE THREAD

**Issue by andcanit** [mozilla/geckodriver#1826]
## System

* Version: geckodriver 0.28.0 (c00d2b6acd3f 2020-11-03 16:29 +0200)
* Platform: Windows 10
* Firefox: 84.0.1
* Selenium: 3.141.59 Java binding

## Testcase

```
WebElement element = driver.findElement(By.id("button-id"));
// .. Navigate to different URL 
FluentWait<WebDriver> wait = new FluentWait<WebDriver>(driver);
wait.until(ExpectedConditions.stalenessOf(element));
```

## Stacktrace

```
org.openqa.selenium.NoSuchElementException: Web element reference not seen before: {"element-6066-11e4-a52e-4f735466cecf":"298d111e-4164-464c-9041-7faa9df878f3"}
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SIMBX-SEL-ASP-5', ip: '10.0.5.52', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_242'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 84.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20201221152838, moz:geckodriverVersion: 0.28.0, moz:headless: true, moz:processID: 736, moz:profile: C:\Users\xyz..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 0139f8ea-1007-4336-9e07-cc729c104620
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:156)
	at org.openqa.selenium.support.ui.ExpectedConditions$24.apply(ExpectedConditions.java:700)
	at org.openqa.selenium.support.ui.ExpectedConditions$24.apply(ExpectedConditions.java:695)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
```

**Comment by whimboo** [comment]
How often does that happen? I assume it's not permanent? Might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1684827.

**Comment by whimboo** [comment]
I created a [test build with the fix included](https://treeherder.allizom.org/jobs?repo=try&revision=bbb6a41f62a3ca31448d43709aa8bdd1af7c7756&searchStr=windows%2Cx64%2Cbuild&selectedTaskRun=fBP0O7aCTTGWjIFBUvxgMQ.0). 

@andcanit, would you mind testing your case with https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/fBP0O7aCTTGWjIFBUvxgMQ/runs/0/artifacts/public/build/target.zip? Just extract the ZIP archive, and specify the Firefox binary in your selenium script. Thanks!

As a workaround for now you can also set the `marionette.actors.enabled` preference to `false`.

**Comment by andcanit** [comment]
Hi, we tested the test build and it seems to have the problem fixed. Thanks!

**Comment by whimboo** [comment]
Thanks a lot and good to hear. The fix is already in the most recent Firefox Nightly, and we will try to get it also fixed in Firefox 85 beta.

**Comment by jtnord** [comment]
still seeing what looks exactly like this with firefox 85 and geckodriverVersion: 0.29.0

can you confirm that this did go into Firefox 85?  (the release notes do not mention anything I can see, and 85 did contain security issues, so not sure if non security fixes got bumped to 86).

**Comment by whimboo** [comment]
Release notes for developers end-up on MDN:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/85#webdriver_conformance_marionette

As the status flag on the bug shows (`firefox85 | --- | fixed`) it is fixed in 85. If something is still broken for you please file a new bug as I already mentioned in my last comment on https://bugzilla.mozilla.org/show_bug.cgi?id=1684827. Thanks.
