### ISSUE TITLE
driver.quit() throws UnreachableBrowserException

### ISSUE THREAD

**Issue by danhumphrey** [mozilla/geckodriver#210]
**Machine:** Windows 10 64bit
**Firefox version:** 48.0.2
**WebDriver version:** 3.0.0-beta3
**geckodriver version:** geckodriver-v0.10.0-win64

I have seen this raised previously, but closed asking for reproduction steps or requesting use of the current geckodriver version. Please let me know if you need more info.

**Reproduction code:**
```java
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class FirefoxCrashOnQuit {

	public static void main(String[] args) {
		System.setProperty("webdriver.gecko.driver",System.getenv("FIREFOX_DRIVER"));
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		WebDriver driver = new FirefoxDriver(capabilities);
		driver.get("http://seleniumhq.org");
		driver.quit();
	}
}
```
**Console output:**
```
Sep 05, 2016 10:29:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1473035370588	Marionette	INFO	Listening on port 2054
1473035371874	Marionette	INFO	startBrowser 78c95da8-cc4a-4ee0-a99b-a19f6bcde3ea
1473035371884	Marionette	INFO	sendAsync 78c95da8-cc4a-4ee0-a99b-a19f6bcde3ea
Sep 05, 2016 10:29:32 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1473035372186	Marionette	INFO	sendAsync 78c95da8-cc4a-4ee0-a99b-a19f6bcde3ea
1473035372243	Marionette	INFO	sendAsync 78c95da8-cc4a-4ee0-a99b-a19f6bcde3ea
[Child 2760] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2046
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:57:44 -0700'
System info: host: 'NSWSYDNTAB09', ip: '10.2.20.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160823121617, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0.2, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 78c95da8-cc4a-4ee0-a99b-a19f6bcde3ea
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:654)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:493)
	at FirefoxCrashOnQuit.main(FirefoxCrashOnQuit.java:12)
Caused by: java.lang.IllegalStateException: UnixUtils may not be used on Windows
	at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:188)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID(UnixProcess.java:222)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$300(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:132)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:597)
	... 3 more
```

**Comment by andreastt** [comment]
I believe this is caused by [bug 1051567](https://bugzilla.mozilla.org/show_bug.cgi?id=1051567), which was fixed last week and uplifted to Firefox 49. An uplift to 48 is unlikely because it’s not a top crash bug.

I would recommend you to use a [Nightly build](https://nightly.mozilla.org/) or Firefox 49 onwards. The more recent the Firefox, generally the better support for Marionette is. Firefox 49 is scheduled for release next week.

**Comment by glannes31** [comment]
Hello , on firefox 49 , it's the same bug

**Comment by gabcastell-tester** [comment]
Hello, I'm using Firefox Nightly 52.0a1, Selenium 3.0.0-beta4 and Geckodriver 0.10.0 and I still get the same message:
**###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052**
Any ideas on this?

**Comment by elgalu** [comment]
Idk about the error however you could use the [official docker-selenium](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.0.0-beta4) or [mine](https://github.com/elgalu/docker-selenium#selenium-3) and stop worrying about setting this up on your own ;)

**Comment by zniff** [comment]
Got the same error today with (java) version 3.0.0 (3.0.0 (build time: 2016-10-13 10:48:57 -0700) and geckodriver 0.11.1

`[Child 26324] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052
`

This error happens after calling:
**`driver.get("<url>");`**

Here the full exception:
```
Error loading page
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
System info: host: 'myComputer', ip: '192.168.1.165', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIADt7TkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc9VXwW7jNhC99ysKn1og5jpJFyi2pzSbBQoETbHZYC8GCIoaSYwpkuWQlv33HUp2bEeylOytJ0v0cMiZ9+bNKCJ47jwUv8wybxt6YygKaJ+VKVktdCM8MDAi05DPLn4uhEb49Y+f4mFnLgLZOOtD2lKB0KHq3hkZrZWc2N9Alnu1prO1Ldst4Mny98Xi1G5/wwq0A3/jHLJ0vS3e4IoV1ksY9j+wzwCdkbahWMM3+1nhivbOAmzCB4nrC+GcVlIEZU3vfTNPK52prWsxR3DCiwD5fC10hFPjWnemTgtluse0pmpRwodnB+XF4KFrk7Ma57CRoE/+sDJAmGPwIOrZaZwGQmP9ilUhOOYqhdV2nv52AnGuwZShoiCvPn4cTg95zOknhwB0Rv5FeQw3hKnUKa/Bx1HYpFZgwhBsua2JRxsuK29r4Ci9coH7aHhQdXJ9fQbnIDJkRD/zYG61xQl0c9sYbQWlTRjKLRG5ss33CswjsTMxc3i7o0u5gOkwXttc6AmuwzpYq5GB98Q4a9DqY3r304SqNNZQdmuoM/CP7SuOx4KASGBjsFR7HjBS3gq6KJdeYPV+llsH5otqcfyfc3wfpVamC4uTZ/BG6ETtd+tSkUj+NZoJYeJCSiDSRkP4ImWBS/ABB/F+4aNCyscW8rvLxePfluoopf+3YWNayh/Md2WIxXi5YIoOsk9f7xNgIrMxfMq0MKtZv7K6gLjQmj8jT7l0KYfDd9s4RaQiW9ZUKoBWGMjBv1H5c3xPZF+pwHbasq8tCi4xfjQBmujiqczHCwpTdUbHKtIGR755A1omnYg+QTo7g/9LtRdWk2rdUyR9AiRqmLaQWHTEBmCGcCi2T9g2mPe1sujSeXejsYCMXoUt0UoDPTGisJKBW69KZbizxPDtePUaaEiJ2C74EehPLtp5ZmnxMWa1atXjn3bxpmXu21r3oJvRiF8Ea4diQpAszwj6oWgpzKYlex+007bSPQ61FVsU5A/mopsDtG14tuU5FCLqMKzEe3gkuh0ph6Pq82aUwvsaoYIikQ9+y7qm0tpfTdmOut5n7u7p/oZdM3EAsx/es1iLrrmO9qPXkO0Lb5xv/Xt7eG7nhNFDOjon9+8ZAal/0ThHWtNKZg/5I3hEDGl4S54fJTEryd7l4pyKd1fghrrMGjg1RzOh4UcTyAPRdpItmbZy1arqm1BFEF5WO45NTTc16yqG5bF2b0L4RSNzlSpoBp+WyzKE5TIV+HIZUcxJx1uJwuXyarG4Xlwul7BJcvAKfiqyN5XCKY67i4zN8i2xLW3wKh9uJz1Rfa2m18NTcNeq5nuZILqHODF27WzPSOVujJ2eX4/GBmxHt8PYQJIa24T04zxKcWL18CWOatx2fb4dc/8yt90kOug53XzXsHmrvjml0ZQ8cWOCoDRMaiYrkKvPnbD++QLpO3s5E3mu0o3FRGcb/A790e9PYmGZFneD+mgvO6rjNuJb0nBSikzpxD6jyiroM937aOv+xB+RYL4vBBqLg22JOEufCx5e5egwx6WvCyI2fSNMDHIHzdEFRteNNIMj1ist9jYV3qGI/wNQSwcITzfdbJkEAAAzEAAAUEsBAhQAFAAICAgAO3tOSU833WyZBAAAMxAAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAzgQAAAAA}, loggingPrefs={server=INFO, performance=INFO, driver=INFO, browser=INFO, client=INFO, profiler=INFO}, appBuildId=20160922113459, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=23900, browserVersion=49.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, marionette.logging=info, platformName=windows_nt, device=desktop}]
Session ID: ce803e4f-f8fd-45cc-85b3-4594f4f25006
org.openqa.selenium.WebDriverException: Error loading page
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
System info: host: 'myComputer', ip: '192.168.1.165', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIADt7TkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc9VXwW7jNhC99ysKn1og5jpJFyi2pzSbBQoETbHZYC8GCIoaSYwpkuWQlv33HUp2bEeylOytJ0v0cMiZ9+bNKCJ47jwUv8wybxt6YygKaJ+VKVktdCM8MDAi05DPLn4uhEb49Y+f4mFnLgLZOOtD2lKB0KHq3hkZrZWc2N9Alnu1prO1Ldst4Mny98Xi1G5/wwq0A3/jHLJ0vS3e4IoV1ksY9j+wzwCdkbahWMM3+1nhivbOAmzCB4nrC+GcVlIEZU3vfTNPK52prWsxR3DCiwD5fC10hFPjWnemTgtluse0pmpRwodnB+XF4KFrk7Ma57CRoE/+sDJAmGPwIOrZaZwGQmP9ilUhOOYqhdV2nv52AnGuwZShoiCvPn4cTg95zOknhwB0Rv5FeQw3hKnUKa/Bx1HYpFZgwhBsua2JRxsuK29r4Ci9coH7aHhQdXJ9fQbnIDJkRD/zYG61xQl0c9sYbQWlTRjKLRG5ss33CswjsTMxc3i7o0u5gOkwXttc6AmuwzpYq5GB98Q4a9DqY3r304SqNNZQdmuoM/CP7SuOx4KASGBjsFR7HjBS3gq6KJdeYPV+llsH5otqcfyfc3wfpVamC4uTZ/BG6ETtd+tSkUj+NZoJYeJCSiDSRkP4ImWBS/ABB/F+4aNCyscW8rvLxePfluoopf+3YWNayh/Md2WIxXi5YIoOsk9f7xNgIrMxfMq0MKtZv7K6gLjQmj8jT7l0KYfDd9s4RaQiW9ZUKoBWGMjBv1H5c3xPZF+pwHbasq8tCi4xfjQBmujiqczHCwpTdUbHKtIGR755A1omnYg+QTo7g/9LtRdWk2rdUyR9AiRqmLaQWHTEBmCGcCi2T9g2mPe1sujSeXejsYCMXoUt0UoDPTGisJKBW69KZbizxPDtePUaaEiJ2C74EehPLtp5ZmnxMWa1atXjn3bxpmXu21r3oJvRiF8Ea4diQpAszwj6oWgpzKYlex+007bSPQ61FVsU5A/mopsDtG14tuU5FCLqMKzEe3gkuh0ph6Pq82aUwvsaoYIikQ9+y7qm0tpfTdmOut5n7u7p/oZdM3EAsx/es1iLrrmO9qPXkO0Lb5xv/Xt7eG7nhNFDOjon9+8ZAal/0ThHWtNKZg/5I3hEDGl4S54fJTEryd7l4pyKd1fghrrMGjg1RzOh4UcTyAPRdpItmbZy1arqm1BFEF5WO45NTTc16yqG5bF2b0L4RSNzlSpoBp+WyzKE5TIV+HIZUcxJx1uJwuXyarG4Xlwul7BJcvAKfiqyN5XCKY67i4zN8i2xLW3wKh9uJz1Rfa2m18NTcNeq5nuZILqHODF27WzPSOVujJ2eX4/GBmxHt8PYQJIa24T04zxKcWL18CWOatx2fb4dc/8yt90kOug53XzXsHmrvjml0ZQ8cWOCoDRMaiYrkKvPnbD++QLpO3s5E3mu0o3FRGcb/A790e9PYmGZFneD+mgvO6rjNuJb0nBSikzpxD6jyiroM937aOv+xB+RYL4vBBqLg22JOEufCx5e5egwx6WvCyI2fSNMDHIHzdEFRteNNIMj1ist9jYV3qGI/wNQSwcITzfdbJkEAAAzEAAAUEsBAhQAFAAICAgAO3tOSU833WyZBAAAMxAAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAzgQAAAAA}, loggingPrefs={server=INFO, performance=INFO, driver=INFO, browser=INFO, client=INFO, profiler=INFO}, appBuildId=20160922113459, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=23900, browserVersion=49.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, marionette.logging=info, platformName=windows_nt, device=desktop}]
Session ID: ce803e4f-f8fd-45cc-85b3-4594f4f25006
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
```

**Comment by andrewdud89** [comment]
Got same problem, but when try click on element.
My issue-[https://github.com/mozilla/geckodriver/issues/289](url)

**Comment by gabcastell-tester** [comment]
same error observed in new Selenium 3.0.1, geckodriver 0.11.1 and Firefox 49.0.2

**Comment by jfrankpa** [comment]
I am also getting the error when clicking on an element that was using the driver.get.   I removed that and the login button worked but then the application halted when trying to click a link that was being found using the link text find by.    I am very confused and really want to get this working so that I can stop flip flopping between FF 46 and FF 49.

**Comment by mefateah** [comment]
The same problem:
selenium: 2.53.1
firefox: 49.0.2

**Comment by andreastt** [comment]
Locking this conversation as the numerous “me too” comments are not helping at all.
