### ISSUE TITLE
Setting timeout durations returns Missing 'type' parameter (IndexOutOfBounds)

### ISSUE THREAD

**Issue by Elmue** [mozilla/geckodriver#511]
## Firefox Version
tested on Firefox 48 and 51

## Gecko Driver
version 0.14

## Platform
Windows 7

## Steps to reproduce -
I execute the same C# code that I have executed before with Selenium 2.48, but now with Selenium 3.2 it does not work anymore.

When I execute (in C#) 
Driver.Manage().Timeouts().ImplicitWait =TimeSpan.FromMilliseconds(30000);
or
Driver.Manage().Timeouts().PageLoad =TimeSpan.FromMilliseconds(30000);

I get very weird errors:
`Missing 'type' parameter (IndexOutOfBounds)`

The exception is not understandable: Is a type missing or is a value out of bounds ?

The value of 30 seconds is surely NOT out of bounds.
This is surely a bug.
________________________________________________________________________

When I remove the setting of the timeouts from my code I get other errors while executing:
```
Actions i_Actions = new Actions(Driver);
i_Actions.Click(Element);
i_Actions.Perform();

```
This time the error is:
`Missing or invalid type argument for pointer action (IndexOutOfBounds)`

Here once again an error that does make any sense.
What index is out of bounds ?
Does an action have bounds ?

**Comment by andreastt** [comment]
Selenium is not following the [WebDriver specificaton](http://w3c.github.io/webdriver/webdriver-spec.html) in this case. It is sending a data structure like `{type: "implicit", ms: 42}` whereas geckodriver is expecting `{implicit: 42}`.

I’ve filed https://github.com/SeleniumHQ/selenium/issues/3607 about this in Selenium. Keeping this open as a tracking bug.

**Comment by jleyba** [comment]
geckodriver 0.15.0 does not accept `{pageLoad: 1}` as [required by the spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-set-timeouts), but it does accept `{"page load": 1}`

```sh
[2017-03-10T07:05:21Z] [FINER] [webdriver.http.Executor] >>>
POST /session/91fe80d7-ef9f-f34b-853e-0e6ae430df03/timeouts HTTP/1.1
accept: application/json; charset=utf-8

{"pageLoad":1}
<<<
HTTP/1.1 400
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 972
date: Fri, 10 Mar 2017 07:05:21 GMT

{"value":{"error":"invalid argument","message":"","stacktrace":"stack backtrace:\n   0:        0x10333879e - backtrace::backtrace::trace::h5d936e38aaf1110e\n   1:        0x103338edc - backtrace::capture::Backtrace::new::h90c05c8c72e0f6cd\n   2:        0x10327cca0 - geckodriver::marionette::MarionetteSession::response::h08aa31b0bbd51dd7\n   3:        0x10327a655 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::h5bcbc41bc7c51981\n   4:        0x103248830 - std::panicking::try::do_call::h532e0d8672b70b60\n   5:        0x1033b970a - __rust_maybe_catch_panic\n   6:        0x103259896 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h4a379663166b1095\n   7:        0x1033b7ba4 - std::sys::imp::thread::Thread::new::thread_start::hf410a68837ea407b\n   8:     0x7fffc07faaaa - _pthread_body\n   9:     0x7fffc07fa9f6 - _pthread_start"}}

[2017-03-10T07:05:21Z] [FINER] [webdriver.http.Executor] >>>
POST /session/91fe80d7-ef9f-f34b-853e-0e6ae430df03/timeouts HTTP/1.1
accept: application/json; charset=utf-8

{"page load":1}
<<<
HTTP/1.1 200
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 13
date: Fri, 10 Mar 2017 07:05:21 GMT

{"value": {}}
```

**Comment by andreastt** [comment]
@jleyba This is now fixed in Firefox 53 onwards: https://bugzilla.mozilla.org/show_bug.cgi?id=1342162

**Comment by MarcinJan** [comment]
I have installed 53.0b8 (64-bit) and it's still not working! 

selenium (3.3.1)
geckodriver-v0.15.0-win64

Marcin

**Comment by andreastt** [comment]
@MarcinJan 53.0b8 might not have the patch unless it’s the latest build from Mozilla. Can you try again with [Nightly](https://nightly.mozilla.org/)?

If it still doesn’t work you need to tell me which language binding you’re using.

**Comment by chrisspen** [comment]
I'm using Selenium 3.3.3, Geckodriver 0.15.0 and Firefox 52.0.2 on Ubuntu 16.04, and I'm getting this same error.

**Comment by andreastt** [comment]
@chrisspen As is suggested in this thread, you need to use a more modern Firefox than 52.

**Comment by Olubolar614** [comment]
I'm still getting the error "Missing Type Parameter". Please find below error logs
Environment
Selenium - v3.4.1
Geckodriver - v0.16.1
Firefox - Version 53
Operating System - Windows 10
[Missing_Type_Parameter Error.txt](https://github.com/mozilla/geckodriver/files/961878/Missing_Type_Parameter.Error.txt)

**Comment by andreastt** [comment]
@Olubolar614 Your attached log doesn’t include trace-level logging.

**Comment by Olubolar614** [comment]
@andreastt I want to change the logging level from info to trace. Can you please send me the steps on how to make the changes via preferences

**Comment by andreastt** [comment]
@Olubolar614 Please see the README: https://github.com/mozilla/geckodriver#firefox-capabilities

The tl;dr is that you need to either pass `-vv` to the geckodriver binary, or set `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` as a capability. Your language binding _may_ have a utility API that lets you set that, otherwise you need to construct a JSON Object.

**Comment by Olubolar614** [comment]
@andreastt Thanks for sharing the trace level log information. I am still getting info level log after setting to capability.Please find below code used and logs retrieved
[Capability Code.txt](https://github.com/mozilla/geckodriver/files/966073/Capability.Code.txt)
[Logs_Info_Level.txt](https://github.com/mozilla/geckodriver/files/966074/Logs_Info_Level.txt)

**Comment by andreastt** [comment]
@Olubolar614 You appear to be setting the capability as _a preference_:

> ```
> options.addPreference("log", "{level: trace}");
> ```

If you look at the source code of the `FirefoxOptions` class, there exists a `setLogLevel` method that apparently lets you set the logging level: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxOptions.java#L352

**Comment by peterdemin** [comment]
Well, that's not `trace` level, as you requested, but maybe `DEBUG` will do?
```
2017-06-07 11:11:39,896 [DEBUG] selenium.webdriver.remote.remote_connection: POST http://127.0.0.1:59657/session/64e55bb2-fb77-4d51-b851-bdc7cd712b49/timeouts {"sessionId": "64e55bb2-fb77-4d51-b851-bdc7cd712b49", "implicit": 2000}
(Pdb) method, parsed_url.path, body, headers
('POST', '/session/64e55bb2-fb77-4d51-b851-bdc7cd712b49/timeouts', '{"sessionId": "64e55bb2-fb77-4d51-b851-bdc7cd712b49", "implicit": 2000}', {'Accept': 'application/json', 'User-Agent': 'Python http auth', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'keep-alive'})
(Pdb) data
b'{"error":"invalid argument","message":"Missing \'type\' parameter"}'
```

**Comment by emesterhazy** [comment]
I am experiencing a similar issue after updating to Selenium 3.4.3. 

## Firefox
Tested version 47 and 54.0.1

## Gecko Driver
Tested with 0.13

## Platform
Windows 7 and Python 2.7.12

## Steps to reproduce

As part of my script I am asking the webdriver to load a URL and implicitly wait.
```py
        browser.get(url)
        browser.implicitly_wait(15)  # seconds
```
Once the script gets to the implicit wait it returns the following error:

```
line 76, in function browser.implicitly_wait(15)  # seconds
line 726, in implicitly_wait  'implicit': int(float(time_to_wait) * 1000)})
line 256, in execute self.error_handler.check_response(response)
line 194, in check_response raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing 'type' parameter
````

## Solution
I ended up rolling back to Selenium 3.0.2, the version I used prior to updating to 3.4.3, which completely resolved the issue.

**Comment by jgraham** [comment]
geckodriver  0.13 is very old now. Bugs are fixed in every version so it's unsurprisingly you are having issues.

**Comment by emesterhazy** [comment]
@jgraham That's a good point. I upgraded to Geckodriver 0.17 and Selenium 3.4.3 and that resolved the issue I described above.

**Comment by GitSIPA** [comment]
I am struggling with doing this. 
With RemoteWebDriver it is working to execute the element.SendKeys("anytext") method. 
On local execution I'm getting an exception:
"Missing 'text' parameter (IndexOutOfBounds)".

Can anybody help me with my problem? 

I am using Selenium 3.4.0 (C#), Firefox 54.0.1 (x86) and Geckodriver 0.17.0.

My method for configuring the browser:
`
var profile = new FirefoxProfile();
var options = new FirefoxOptions();
options.AddAdditionalCapability("acceptSslCerts", true, true);            
options.AddAdditionalCapability("acceptInsecureCerts", true, true);
options.SetPreference("intl.accept_languages", "en-GB");
options.Profile = profile;
options.LogLevel = FirefoxDriverLogLevel.Trace;
var driver = new FirefoxDriver(options);
driver.Manage().Window.Maximize();
return driver;`

`
1499337658809   geckodriver::marionette TRACE   -> 72:[0,154,"findElement",{"usi
ng":"css selector","value":"#tbTitle_txtBox"}]
1499337658812   geckodriver::marionette TRACE   <- [1,154,null,{"value":{"elemen
t-6066-11e4-a52e-4f735466cecf":"ac590159-c07f-4441-8862-857bd08fb95a","ELEMENT":
"ac590159-c07f-4441-8862-857bd08fb95a"}}]
1499337658812   webdriver::server       DEBUG   <- 200 OK {"value":{"element-606
6-11e4-a52e-4f735466cecf":"ac590159-c07f-4441-8862-857bd08fb95a"}}
1499337658813   webdriver::server       DEBUG   -> POST /session/791b3db2-8399-4
f12-8fb6-9fa9b22411ea/element {"using":"css selector","value":"#tbTitle_txtBox"}

1499337658813   geckodriver::marionette TRACE   -> 72:[0,155,"findElement",{"usi
ng":"css selector","value":"#tbTitle_txtBox"}]
1499337658816   geckodriver::marionette TRACE   <- [1,155,null,{"value":{"elemen
t-6066-11e4-a52e-4f735466cecf":"ac590159-c07f-4441-8862-857bd08fb95a","ELEMENT":
"ac590159-c07f-4441-8862-857bd08fb95a"}}]
1499337658816   webdriver::server       DEBUG   <- 200 OK {"value":{"element-606
6-11e4-a52e-4f735466cecf":"ac590159-c07f-4441-8862-857bd08fb95a"}}
1499337658819   webdriver::server       DEBUG   -> POST /session/791b3db2-8399-4
f12-8fb6-9fa9b22411ea/element/ac590159-c07f-4441-8862-857bd08fb95a/value {"value
":["H","e","r","r"]}
1499337658821   webdriver::server       DEBUG   <- 400 Bad Request {"value":{"er
ror":"invalid argument","message":"Missing 'text' parameter","stacktrace":"stack
backtrace:\n   0:           0x4bd56f - <no info>\n   1:           0x4bdcc9 - <n
o info>\n   2:           0x4a57d6 - <no info>\n   3:           0x419efe - <no in
fo>\n   4:           0x433d30 - <no info>\n   5:           0x426345 - <no info>\
n   6:           0x405f3a - <no info>\n   7:           0x6db3d9 - <no info>\n
8:           0x417af5 - <no info>\n   9:           0x6d56d3 - <no info>\n  10:
       0x76f059cd - BaseThreadInitThunk"}}
`

**Comment by bahadurbaniya** [comment]
@GitSIPA  Selenium 3.4.3 (C#) is not needed which does not exist as of 7 July 2017. Only python ruby language bindings exist.

**Comment by nkpatnis** [comment]
Geckodriver 0.17 and and Java Selenium 3.4.0 same issue

**Comment by akashghule** [comment]
I was also facing the same issue, but taking latest ff update (55.0.3) and latest geckodriver (0.18.0) solved my problem.

**Comment by andreastt** [comment]
Do note that this bug is closed and has been fixed. Locking.
