### ISSUE TITLE
active element

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#52]
This is with Firefox 45, Wires 0.6.2
```
-> GET session/0a0be41a-490e-7a42-b5e9-48f4589ed26b/element/active
1457560012250	Marionette	TRACE	conn0 -> [0,3,"getActiveElement",{}]
1457560012252	Marionette	TRACE	conn0 <- [1,3,null,{"value":"e4c34c1e-7982-7f4c-ba24-0b9f74bf78a7"}]
<- {"error":"unknown error","message":"Failed to convert data to an object"}
```

**Comment by andreastt** [comment]
@titusfortner Does this happen in [Nightly](https://nightly.mozilla.org/)?

**Comment by andreastt** [comment]
I fixed up _Get Active Element_ to be spec compatible in [bug 1274550](https://bugzilla.mozilla.org/show_bug.cgi?id=1274550) FWIW.

**Comment by titusfortner** [comment]
Oh, I just re-filed this https://bugzilla.mozilla.org/show_bug.cgi?id=1280516
Should I file here or there in the future?

Yes, still happening for me Macos, geckodriver 0.8, FF49

**Comment by titusfortner** [comment]
Fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1274550
