### ISSUE TITLE
Capabilities negotiation fails on macOS because application.ini file is not found

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#638]
## Firefox Version
55.0a1 (2017-04-11) (64-bit)

## Platform
OS X

## Steps to reproduce -
Follow the steps in the following gist using the latest released selenium version (3.3.1):

https://gist.github.com/shs96c/1acc3165bd6e562c33525955d616d2df

I'd expect a FirefoxDriver to start. Instead, no session can be created.

**Comment by shs96c** [comment]
This also happen with HEAD of master in the selenium project.

**Comment by andreastt** [comment]
Thanks for alerting us! Do you have a trace-level log we could look at?

**Comment by shs96c** [comment]
```
1491993151159	webdriver::httpapi	DEBUG	Creating routes
1491993151213	hyper::server	DEBUG	threads = 10
1491993151213	geckodriver	INFO	Listening on 127.0.0.1:4444
1491993184105	hyper::server	DEBUG	Incoming stream
1491993184108	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session") Http11
1491993184108	hyper::server::request	DEBUG	Headers { Content-Type: application/json; charset=utf-8
, Content-Length: 510
, Host: localhost:4444
, Connection: Keep-Alive
, User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
, Accept-Encoding: gzip,deflate
, }
1491993184108	webdriver::server	DEBUG	Got request POST AbsolutePath("/session")
1491993184108	webdriver::command	DEBUG	Got request body {
  "desiredCapabilities": {
    "acceptInsecureCerts": true,
    "browserName": "firefox",
    "version": "",
    "platform": "ANY"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "acceptInsecureCerts": true,
      "browserName": "firefox",
      "version": "",
      "platform": "ANY"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "acceptInsecureCerts": true
    },
    "firstMatch": [
      {
        "browserName": "firefox"
      }
    ]
  }
}
1491993184395	webdriver::server	DEBUG	Returning status InternalServerError
1491993184395	webdriver::server	DEBUG	Returning body {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":"stack backtrace:\n   0:        0x10b042b51 - backtrace::backtrace::trace<closure>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:42\n   1:        0x10b044044 - backtrace::capture::Backtrace::new::h8ca3ad60a3bf61a1\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/lib.rs:101\n   2:        0x10afb8351 - webdriver::error::{{impl}}::new<&str>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.0/src/error.rs:232\n   3:        0x10afbffe5 - geckodriver::marionette::{{impl}}::create_connection\n                        at /Users/shs/src/geckodriver/src/marionette.rs:277\n   4:        0x10afc2fb0 - geckodriver::marionette::{{impl}}::handle_command\n                        at /Users/shs/src/geckodriver/src/marionette.rs:409\n   5:        0x10af5dc1f - webdriver::server::{{impl}}::run<geckodriver::marionette::MarionetteHandler,geckodriver::marionette::GeckoExtensionRoute>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.0/src/server.rs:65\n   6:        0x10afb9128 - webdriver::server::start::{{closure}}<geckodriver::marionette::MarionetteHandler,geckodriver::marionette::GeckoExtensionRoute>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.0/src/server.rs:254\n   7:        0x10afac65a - std::panic::{{impl}}::call_once<(),closure>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panic.rs:296\n   8:        0x10aee7619 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panicking.rs:460\n   9:        0x10b59e78a - __rust_maybe_catch_panic\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libpanic_unwind/lib.rs:98\n  10:        0x10aee6dc3 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panicking.rs:436\n  11:        0x10aee3d24 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panic.rs:361\n  12:        0x10aee610b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/thread/mod.rs:357\n  13:        0x10af43912 - alloc::boxed::{{impl}}::call_box<(),closure>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/liballoc/boxed.rs:614\n  14:        0x10b59cbb4 - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/sys_common/thread.rs:21\n  15:     0x7fff9dc049ae - _pthread_body\n  16:     0x7fff9dc048fa - _pthread_start"}}
1491993184396	hyper::server::response	DEBUG	writing head: Http11 InternalServerError
1491993184397	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 3195
, Date: Wed, 12 Apr 2017 10:33:04 GMT
, }]
1491993184397	hyper::server::response	DEBUG	write 3195 bytes
1491993184397	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:61564
1491993184397	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:61564
```

**Comment by andreastt** [comment]
I haven’t sat down and looked at this in detail yet, but I suspect it is because it passes invalid fields, such as `desiredCapabilities` and `requiredCapabilities` inside the top-level `capabilities` field, which is meant to hold `alwaysMatch`/`firstMatch`.

**Comment by shs96c** [comment]
There's nothing in [Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities) that says additional fields are incorrect. It only talks about what must be there.

**Comment by shs96c** [comment]
And running the same test with `acceptInsecureCerts` in the new session payload gets a running firefoxdriver session:

```
1491995298269	webdriver::httpapi	DEBUG	Creating routes
1491995298324	hyper::server	DEBUG	threads = 10
1491995298324	geckodriver	INFO	Listening on 127.0.0.1:4444
1491995322309	hyper::server	DEBUG	Incoming stream
1491995322312	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session") Http11
1491995322312	hyper::server::request	DEBUG	Headers { Content-Type: application/json; charset=utf-8
, Content-Length: 403
, Host: localhost:4444
, Connection: Keep-Alive
, User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
, Accept-Encoding: gzip,deflate
, }
1491995322313	webdriver::server	DEBUG	Got request POST AbsolutePath("/session")
1491995322313	webdriver::command	DEBUG	Got request body {
  "desiredCapabilities": {
    "browserName": "firefox",
    "version": "",
    "platform": "ANY"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "browserName": "firefox",
      "version": "",
      "platform": "ANY"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {},
    "firstMatch": [
      {
        "browserName": "firefox"
      }
    ]
  }
}
1491995322629	mozprofile::profile	INFO	Using profile path /var/folders/6m/70gf06zx02xgxzyrkwpmvwth0000gn/T/rust_mozprofile.cO5symq7aDNR
1491995322631	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1491995322645	geckodriver::marionette	INFO	Connecting to Marionette on localhost:64390
1491995322646	geckodriver::marionette	DEBUG	  connection attempt 0/600
1491995322748	geckodriver::marionette	DEBUG	  connection attempt 1/600
1491995322850	geckodriver::marionette	DEBUG	  connection attempt 2/600
1491995322953	geckodriver::marionette	DEBUG	  connection attempt 3/600
1491995323056	geckodriver::marionette	DEBUG	  connection attempt 4/600
1491995323157	geckodriver::marionette	DEBUG	  connection attempt 5/600
1491995323259	geckodriver::marionette	DEBUG	  connection attempt 6/600
1491995323365	geckodriver::marionette	DEBUG	  connection attempt 7/600
1491995323466	geckodriver::marionette	DEBUG	  connection attempt 8/600
1491995323570	geckodriver::marionette	DEBUG	  connection attempt 9/600
1491995323675	geckodriver::marionette	DEBUG	  connection attempt 10/600
1491995323780	geckodriver::marionette	DEBUG	  connection attempt 11/600
1491995323882	geckodriver::marionette	DEBUG	  connection attempt 12/600
1491995323986	geckodriver::marionette	DEBUG	  connection attempt 13/600
1491995324090	geckodriver::marionette	DEBUG	  connection attempt 14/600
1491995324191	geckodriver::marionette	DEBUG	  connection attempt 15/600
1491995324292	geckodriver::marionette	DEBUG	  connection attempt 16/600
1491995324397	geckodriver::marionette	DEBUG	  connection attempt 17/600
1491995324499	geckodriver::marionette	DEBUG	  connection attempt 18/600
1491995324601	geckodriver::marionette	DEBUG	  connection attempt 19/600
1491995324704	geckodriver::marionette	DEBUG	  connection attempt 20/600
1491995324807	geckodriver::marionette	DEBUG	  connection attempt 21/600
1491995324911	geckodriver::marionette	DEBUG	  connection attempt 22/600
1491995325016	geckodriver::marionette	DEBUG	  connection attempt 23/600
1491995325119	geckodriver::marionette	DEBUG	  connection attempt 24/600
1491995325222	geckodriver::marionette	DEBUG	  connection attempt 25/600
1491995325328	geckodriver::marionette	DEBUG	  connection attempt 26/600
1491995325377	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1491995325378	Marionette	INFO	Listening on port 64390
1491995325437	geckodriver::marionette	DEBUG	TCP connection established
1491995325465	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:64453
1491995325532	geckodriver::marionette	DEBUG	← {"applicationType":"gecko","marionetteProtocol":3}
1491995325533	geckodriver::marionette	DEBUG	→ 109:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]
1491995325634	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":7340,"moz:profile":"/var/folders/6m/70gf06zx02xgxzyrkwpmvwth0000gn/T/rust_mozprofile.cO5symq7aDNR","moz:accessibilityChecks":false}
1491995325987	geckodriver::marionette	DEBUG	← [1,1,null,{"sessionId":"49de22ee-9adf-6c40-85c4-6aeea9cdc9fe","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":7340,"moz:profile":"/var/folders/6m/70gf06zx02xgxzyrkwpmvwth0000gn/T/rust_mozprofile.cO5symq7aDNR","moz:accessibilityChecks":false}}]
1491995325988	webdriver::server	DEBUG	Returning status Ok
1491995325989	webdriver::server	DEBUG	Returning body {"value": {"sessionId":"49de22ee-9adf-6c40-85c4-6aeea9cdc9fe","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":7340,"moz:profile":"/var/folders/6m/70gf06zx02xgxzyrkwpmvwth0000gn/T/rust_mozprofile.cO5symq7aDNR","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1491995325989	hyper::server::response	DEBUG	writing head: Http11 Ok
1491995325990	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 484
, Date: Wed, 12 Apr 2017 11:08:45 GMT
, }]
1491995325990	hyper::server::response	DEBUG	write 484 bytes
1491995325990	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:64389
1491995325990	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:64389
1491995326231	hyper::server	DEBUG	Incoming stream
1491995326232	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session/49de22ee-9adf-6c40-85c4-6aeea9cdc9fe/url") Http11
1491995326232	hyper::server::request	DEBUG	Headers { Content-Type: application/json; charset=utf-8
, Content-Length: 33
, Host: localhost:4444
, Connection: Keep-Alive
, User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
, Accept-Encoding: gzip,deflate
, }
1491995326232	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/49de22ee-9adf-6c40-85c4-6aeea9cdc9fe/url")
1491995326234	webdriver::command	DEBUG	Got request body {"url":"http://www.google.co.uk"}
1491995326234	geckodriver::marionette	DEBUG	→ 45:[0,2,"get",{"url":"http://www.google.co.uk"}]
2017-04-12 12:08:46.243 plugin-container[7341:919909] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa23b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-12 12:08:46.250 plugin-container[7341:919909] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa503, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1491995327764	geckodriver::marionette	DEBUG	← [1,2,null,{}]
1491995327764	webdriver::server	DEBUG	Returning status Ok
1491995327764	webdriver::server	DEBUG	Returning body {"value": {}}
1491995327764	hyper::server::response	DEBUG	writing head: Http11 Ok
1491995327764	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 13
, Date: Wed, 12 Apr 2017 11:08:47 GMT
, }]
1491995327765	hyper::server::response	DEBUG	write 13 bytes
1491995327765	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:64457
1491995327765	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:64457
```

**Comment by shs96c** [comment]
It's something about being able to set `acceptInsecureCerts` to `true`. Setting the field to `false` also starts Firefox properly through geckodriver.

**Comment by shs96c** [comment]
Debugging further: this seems to be because `acceptInsecureCerts` is in the `alwaysMatch` field, as this also fails.

```
curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session
```

**Comment by AutomatedTester** [comment]
I have fixed the issue. Just got 

```bash

(certs) dburns in ~/development/selenium/py on master ● λ curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session
1492104262571	mozprofile::profile	INFO	Using profile path /var/folders/7n/2f615rtj42l0ppz5jg_nch0c0000gp/T/rust_mozprofile.E9ckR668QH9l
1492104262572	geckodriver::marionette	INFO	Starting browser /Users/dburns/development/mozilla-central/obj-ff-dbg.noindex/dist/Nightly.app/Contents/MacOS/firefox-bin with args []
1492104262576	geckodriver::marionette	INFO	Connecting to Marionette on localhost:49615
1492104264903	Marionette	INFO	Listening on port 49615
1492104265010	Marionette	WARN	TLS certificate errors will be ignored for this session
{"value": {"sessionId":"e5cdf5ec-0fe4-cd4f-8c63-83cd73f769c8","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":81043,"moz:profile":"/var/folders/7n/2f615rtj42l0ppz5jg_nch0c0000gp/T/rust_mozprofile.E9ckR668QH9l","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}%                                                                            2017-04-13 18:24:25.407 plugin-container[81044:5557578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x953b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-13 18:24:25.408 plugin-container[81044:5557578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9903, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

**Comment by andreastt** [comment]
I don’t think I see the problem here, or at least I’m not able to reproduce it. Setting `acceptInsecureCerts` in `alwaysMatch` appears to work just fine, even if I let geckodriver pick up Firefox Nightly from `PATH`:

```
% PATH=/home/ato/src/gecko/obj-x86_64-pc-linux-gnu/dist/bin:$PATH cargo run -- -vv &
[1] 18938
%     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/geckodriver -vv`
1492537624389   webdriver::httpapi      DEBUG   Creating routes
1492537624426   geckodriver     INFO    Listening on 127.0.0.1:4444
% curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session
1492537628841   webdriver::server       DEBUG   Got request POST AbsolutePath("/session")
1492537628842   webdriver::command      DEBUG   Got request body {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}
1492537629023   geckodriver::marionette INFO    Starting browser /home/ato/src/gecko/obj-x86_64-pc-linux-gnu/dist/bin/firefox with args ["-marionette"]
1492537630546   Marionette      DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1492537630546   Marionette      INFO    Listening on port 36583
1492537630628   geckodriver::marionette DEBUG   Connected to Marionette on localhost:36583
1492537630672   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:39990
1492537630676   geckodriver::marionette TRACE   ← {"applicationType":"gecko","marionetteProtocol":3}
1492537630676   geckodriver::marionette TRACE   → 115:[0,1,"newSession",{"acceptInsecureCerts":true,"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true}}}]
1492537630682   Marionette      TRACE   0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true}}}]
1492537630684   Marionette      CONFIG  Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"linux","platformVersion":"4.9.0-2-amd64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":19056,"moz:profile":"/tmp/rust_mozprofile.oNTcRSuij0dC","moz:accessibilityChecks":false}
1492537630684   Marionette      WARN    TLS certificate errors will be ignored for this session
1492537630726   Marionette      TRACE   0 <- [1,1,null,{"sessionId":"c32fa94f-1b6d-4fee-b3ca-3e108459ec14","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"linux","platformVersion":"4.9.0-2-amd64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":19056,"moz:profile":"/tmp/rust_mozprofile.oNTcRSuij0dC","moz:accessibilityChecks":false}}]
1492537630731   geckodriver::marionette TRACE   ← [1,1,null,{"sessionId":"c32fa94f-1b6d-4fee-b3ca-3e108459ec14","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"linux","platformVersion":"4.9.0-2-amd64","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":19056,"moz:profile":"/tmp/rust_mozprofile.oNTcRSuij0dC","moz:accessibilityChecks":false}}]
1492537630731   webdriver::server       DEBUG   Returning status Ok
1492537630731   webdriver::server       DEBUG   Returning body {"value": {"sessionId":"c32fa94f-1b6d-4fee-b3ca-3e108459ec14","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":19056,"moz:profile":"/tmp/rust_mozprofile.oNTcRSuij0dC","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.9.0-2-amd64","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
{"value": {"sessionId":"c32fa94f-1b6d-4fee-b3ca-3e108459ec14","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":19056,"moz:profile":"/tmp/rust_mozprofile.oNTcRSuij0dC","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.9.0-2-amd64","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
```

As far as I can tell, https://github.com/mozilla/webdriver-rust/pull/91 doesn’t do the right thing, so I wonder if this could be a system-dependent problem that is only present on macOS. @jgraham suggested it could be related [mozversion](https://github.com/jgraham/mozversion) not picking up the correct .ini file, which would explain a lot of things.

I wonder if you could try re-running this test on macOS with modifying `PATH` to pick up Firefox Nightly that way?

**Comment by shs96c** [comment]
@andreastt, the value must be `true` for the bug to be shown. You should be able to use the curl example from above.

This still happens with Nightly on OS X with HEAD of master of gecko driver:

```
./target/debug/geckodriver --log trace
1492540733633	webdriver::httpapi	DEBUG	Creating routes
1492540733681	geckodriver	INFO	Listening on 127.0.0.1:4444
1492540746583	webdriver::server	DEBUG	Got request POST AbsolutePath("/session")
1492540746584	webdriver::command	DEBUG	Got request body {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}
1492540746753	webdriver::server	DEBUG	Returning status InternalServerError
1492540746753	webdriver::server	DEBUG	Returning body {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":"stack backtrace:\n   0:        0x10c2f3f71 - backtrace::backtrace::trace<closure>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:42\n   1:        0x10c2f5464 - backtrace::capture::Backtrace::new::h8ca3ad60a3bf61a1\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/lib.rs:101\n   2:        0x10c269451 - webdriver::error::{{impl}}::new<&str>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.1/src/error.rs:232\n   3:        0x10c271155 - geckodriver::marionette::{{impl}}::create_connection\n                        at /Users/shs/src/geckodriver/src/marionette.rs:277\n   4:        0x10c274160 - geckodriver::marionette::{{impl}}::handle_command\n                        at /Users/shs/src/geckodriver/src/marionette.rs:413\n   5:        0x10c20ed0f - webdriver::server::{{impl}}::run<geckodriver::marionette::MarionetteHandler,geckodriver::marionette::GeckoExtensionRoute>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.1/src/server.rs:65\n   6:        0x10c26a228 - webdriver::server::start::{{closure}}<geckodriver::marionette::MarionetteHandler,geckodriver::marionette::GeckoExtensionRoute>\n                        at /Users/shs/.cargo/registry/src/github.com-1ecc6299db9ec823/webdriver-0.25.1/src/server.rs:254\n   7:        0x10c25d5da - std::panic::{{impl}}::call_once<(),closure>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panic.rs:296\n   8:        0x10c198759 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panicking.rs:460\n   9:        0x10c84f7ba - __rust_maybe_catch_panic\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libpanic_unwind/lib.rs:98\n  10:        0x10c197d13 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panicking.rs:436\n  11:        0x10c194bb4 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/panic.rs:361\n  12:        0x10c19705b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/thread/mod.rs:357\n  13:        0x10c1f4982 - alloc::boxed::{{impl}}::call_box<(),closure>\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/liballoc/boxed.rs:614\n  14:        0x10c84dbe4 - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /private/tmp/rust-20170317-3971-sqpojh/rustc-1.16.0-src/src/libstd/sys_common/thread.rs:21\n  15:     0x7fffd63e09ae - _pthread_body\n  16:     0x7fffd63e08fa - _pthread_start"}}
```

Caused by:

```
curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session
```

**Comment by shs96c** [comment]
Confirming that this works on Linux but still fails on OS X.

**Comment by jgraham** [comment]
https://github.com/jgraham/mozversion/pull/2 will fix this once I make a new mozversion release.

**Comment by jgraham** [comment]
This should be fixed in mozversion 0.1.1. Please `cargo update`, recompile, test and close if appropriate.

**Comment by andreastt** [comment]
Updated dependencies in https://github.com/mozilla/geckodriver/commit/363cf9ed793e5fb1530081869a054905b5e4baa8. Should be fixed on master now.
