### ISSUE TITLE
setWindowRect (setPosition) not working with geckodriver 0.16

### ISSUE THREAD

**Issue by pbi-qfs** [mozilla/geckodriver#676]
## Firefox Version
52esr (52.1.0)
53.0
54.0b1
55 (nightly)

## Platform
macOS

## Steps to reproduce -
Try to set the window position on any web site (e.g. with Selenium 3.4.0):

```java
driver.get("http://www.mozilla.com")
driver.manage().window().setPosition(new Point(100,100))
```
Expected: Window is moved to (100,100)

Current behaviour: On FF53+, the setWindowRect is simply ignored, on FF 52esr, a WebdriverException is thrown:

```
setWindowRect
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Elektrik.local', ip: '192.168.189.25', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.AAehoRE933b4, rotatable=false, timeouts={implicit=0.0, page load=300000.0, script=30000.0}, pageLoadStrategy=eager, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.1.0, platformVersion=14.5.0, moz:processID=67261.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 6ee8e160-b590-d149-ad2c-e603b142b025
at org.openqa.selenium.remote.http.W3CHttpResponseCodec(createException:150)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec(decode:115)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec(decode:45)
at org.openqa.selenium.remote.HttpCommandExecutor(execute:164)
at org.openqa.selenium.remote.service.DriverCommandExecutor(execute:82)
at org.openqa.selenium.remote.RemoteWebDriver(execute:637)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow(setPosition:895)
```

Neither behavior is expected...

**Comment by andreastt** [comment]
It’s hard to know what’s wrong because you did not attach a trace-level geckodriver log.

**Comment by jimevans** [comment]
Possible dupe of #343?

**Comment by pbi-qfs** [comment]
Here they are:

On FF53:

```
1493047918979	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:59281
1493047918994	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:59299
1493047919000	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1493047919000	geckodriver::marionette	TRACE	→ 217:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefo1493047919004	Marionette	TRACE	conn0 -> [0,x","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","pageLoadStrategy":"eager"}},"pageLoadStrategy":"eager"}]
1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","pageLoadStrategy":"eager"}},"pageLoadStrategy":"eager"}]
1493047919007	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"14.5.0","pageLoadStrategy":"eager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":69061,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.ntDXFmYR9Hto","moz:accessibilityChecks":false}
1493047919007	Marionette	WARN	TLS certificate errors will be ignored for this session
1493047919326	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"e4c3816b-2f9a-fe43-9d8b-dc8f00793dc4","capabilities":{"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"14.5.0","pageLoadStrategy":"e1493047919327	geckodriver::marionette	TRACE	ager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":69061,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.ntDXFmYR9Hto","moz:accessibilityChecks":false}}]
← [1,1,null,{"sessionId":"e4c3816b-2f9a-fe43-9d8b-dc8f00793dc4","capabilities":{"browserName":"firefox","browserVersion":"53.0","platformName":"darwin","platformVersion":"14.5.0","pageLoadStrategy":"eager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":69061,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.ntDXFmYR9Hto","moz:accessibilityChecks":false}}]
1493047919327	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"e4c3816b-2f9a-fe43-9d8b-dc8f00793dc4","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"53.0","moz:accessibilityChecks":false,"moz:processID":69061,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.ntDXFmYR9Hto","pageLoadStrategy":"eager","platformName":"darwin","platformVersion":"14.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1493047919387	webdriver::server	DEBUG	→ POST /session/e4c1493047919388	Marionette	TRACE	conn03816b-2f9a-fe43-9d8b-dc8f00793dc4/url {"url":" -> [0,2,"get",{"url":"http://www.mozilla.com"}]
http://www.mozilla.com"}
1493047919387	geckodriver::marionette	TRACE	→ 44:[0,2,"get",{"url":"http://www.mozilla.com"}]
2017-04-24 17:31:59.395 plugin-container[69062:1823014] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9643, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-24 17:31:59.396 plugin-container[69062:1823014] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d27, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-24 17:31:59.396 plugin-container[69062:1823014] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
1493047920973	Marionette	TRACE	conn0 <- [1,2,null,{}]
1493047920975	geckodriver::marionette	TRACE	← [1,2,null,{}]
1493047920975	webdriver::server	DEBUG	← 200 OK {"value": {}}
1493047920997	webdriver::server	DEBUG	→ POST /session/e4c3816b-2f9a-fe43-9d8b1493047920999	Marionette	TRACE	conn0 -> [0,3,"setWindowRect",{"height":null-dc8f00793dc4/window/rect {","width":null,"x":null,"y":null}]
script":"window.screenX = arguments[0]; window.screenY = arguments[1]","args":[100,100]}
1493047920998	geckodriver::marionette	TRACE	→ 68:[0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]
1493047921000	geckodriver::marionette	TRACE	← [1,3,null,{"x":4,"y":23,"width":1280,"height":877}]
1493047921000	webdriver::server	DEBUG	← 200 OK {"value": {}}
1493047921000	Marionette	TRACE	conn0 <- [1,3,null,{"x":4,"y":23,"width":1280,"height":877}]
```

On FF52esr:

```
1493047793411	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:59110
1493047793410	DeferredSave.extensions.json	DEBUG	Starting write
1493047793427	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:59119
1493047793449	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1493047793449	geckodriver::marionette	TRACE	→ 217:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","pageLoadStrategy":"eager"}},"pageLoadStrategy":"eager"}]
1493047793454	Marionette	TRACE	conn0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","pageLoadStrategy":"eager"}},"pageLoadStrategy":"eager"}]
1493047793458	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"52.1.0","platformName":"darwin","platformVersion":"14.5.0","pageLoadStrategy":"eager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":68940,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.Rd7APQ4nuRTK","moz:accessibilityChecks":false}
1493047793459	Marionette	WARN	TLS certificate errors will be ignored for this session
1493047793528	DeferredSave.extensions.json	DEBUG	Write succeeded
1493047793529	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1493047794639	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"c7c43142-8683-9b42-a55e-65c5846fc00f","capabilities":{"browserName":"firefox","browserVersion":"52.1.0","platformName":"darwin","platformVersion":"14.5.0","pageLoadStrategy":"eager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":68940,"moz:profile":"/var/folders/j3/glwdgbj17jl31493047794639	geckodriver::marionette	TRACE	← [1,1,null,{"sessionId":"c7c43142-8683-9b42-a55e-65c5846fc00f","capabilities":{"browserName":"firefox","browserVersion":"52.1.0","platformName":"darwin","platformVersion":"14.5.0","pal1k1ps2tb34m000172/T/rust_mozprofile.Rd7APQ4nuRTK","moz:accessibilityChecks":false}}]
geLoadStrategy":"eager","acceptInsecureCerts":true,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":68940,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.Rd7APQ4nuRTK","moz:accessibilityChecks":false}}]
1493047794639	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"c7c43142-8683-9b42-a55e-65c5846fc00f","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"52.1.0","moz:accessibilityChecks":false,"moz:processID":68940,"moz:profile":"/var/folders/j3/glwdgbj17jl3l1k1ps2tb34m000172/T/rust_mozprofile.Rd7APQ4nuRTK","pageLoadStrategy":"eager","platformName":"darwin","platformVersion":"14.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}}
1493047794695	webdriver::server	DEBUG	→ POST 1493047794696	Marionette	TRACE	conn0 -> [0,2,/session/c7c43142-8683-9b42-a55e-65c5846fc00f/url {"url":"http://www.mozilla.com"}
"get",{"url":"http://www.mozilla.com"}]
1493047794696	geckodriver::marionette	TRACE	→ 44:[0,2,"get",{"url":"http://www.mozilla.com"}]
2017-04-24 17:29:54.719 plugin-container[68942:1820553] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x4c3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-24 17:29:54.719 plugin-container[68942:1820553] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9a17, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-24 17:29:54.719 plugin-container[68942:1820553] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
1493047796771	Marionet1493047796772te	TRACE	conn0 <- [1,2,null,{}]
	geckodriver::marionette	TRACE	← [1,2,null,{}]
1493047796772	webdriver::server	DEBUG	← 200 OK {"value": {}}
1493047796790	webdriver::server	DEBUG	→ POST /session/c7c43142-8683-9b42-a55e-65c5846fc00f/window/rect {"script":"window.screenX = arguments[0]; window.screenY = arguments[1]","args":[100,100]}
1493047796791	Marionette	TRACE	conn0 -> [0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]
1493047796792	Marionette	TR1493047796790	geckodriver::marionetteACE	conn0 <- [1,3,{"error":"unknown command","message":"setWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@re	TRACE	→ 68:[0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]
1493047796793	geckodriver::marionette	TRACE	← [1,3,{"error":"unknown command","message":"setWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nsource://gre/modules/Task.jsm:277:3\ncreateAsyncFunctionTa/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjecskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modultReady/<@chrome://marionette/content/server.js -> resource://deves/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjtools/shared/transport/transport.js:483:11\nexportsectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:4.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource:83:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null//gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeD]
1493047796806	webdriver::server	DEBUG	← 404 Not Found {"value":{"error":"unknown error","message":"setWindowRect","stac3 (17:29:56.836) PoolThread-1 de.qfs.apps.qftest.shared.PerformanceLog.endPeriod(String,long): (#219) Mismatched pop: script
ktrace":"evToolsUtils.js:101:14\n"},null]
stack backtrace:\n   0:        0x106da437e - backtrace::backtrace::trace::h76b688ec9dd0c4e2\n   1:        0x106da4abc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:        0x106d57eaf - webdriver::error::WebDriverError::new::h6e7bc24f03499973\n   3:        0x106d687cb - geckodriver::marionette::MarionetteSession::response::h06a886e7e8d17c71\n   4:        0x106d66663 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::h1551b734f4cde0a0\n   5:        0x106d58340 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::h89f46c6cb17a6c48\n   6:        0x106d2bdcd - std::panicking::try::do_call::h20be620158d9b55a\n   7:        0x106ece5ba - __rust_maybe_catch_panic\n   8:        0x106d3aaea - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h4fac0ee9906c8727\n   9:        0x106ecca14 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f\n  10:     0x7fff88740059 - _pthread_body\n  11:     0x7fff8873ffd6 - _pthread_start"}}
```
`1493047796790	webdriver::server	DEBUG	→ POST /session/c7c43142-8683-9b42-a55e-65c5846fc00f/window/rect {"script":"window.screenX = arguments[0]; window.screenY = arguments[1]","args":[100,100]}` and 
`[0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]` doesn't really look right...

Seems like selenium is not providing the parameters here as it should, isn't it?

**Comment by andreastt** [comment]
> Seems like selenium is not providing the parameters here as it should, isn't it?

That would be my guess too. The expected input here would be `{"x": 100,"y": 100}`.

Furthermore, the Set Window Rect command is one of those special ones that you can run with null values on all parameters, so this is why geckodriver isn’t returning an ‘invalid argument’ error.

Unfortunately the command isn’t support in Firefox 52 ESR, so you’ll have to use a newer Firefox.

You didn’t say which language binding you’re using?

**Comment by pbi-qfs** [comment]
I'm using the java bindings. (and the problem seems to be related [these lines](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/W3CHttpCommandCodec.java#L267-L271), so I opened an issue there: SeleniumHQ/selenium#3893)

Firefox 52esr dates back 5 days, so it's not that old :)

Is the future policy that you need a special geckodriver for each firefox version? (Before geckodriver the latest FF release, the previous release, the latest ESR release and the previous ESR release were supported by Selenium - somehow a minimum, if you want to tests your webapps on Firefox in a business environment)

**Comment by andreastt** [comment]
Thanks for investigating and filing a bug on Selenium (-:

> Firefox 52esr dates back 5 days, so it's not that old :)

We release regular security updates to Extended Support Releases, but no new features are uplifted.

> Is the future policy that you need a special geckodriver for each firefox version?

The old FirefoxDriver relied on XUL add-on technology that is going away with Firefox 57. It also does not support the new multi-processing architecture that was introduced from Firefox 43. If it is not the case already, it will be the case very soon that FirefoxDriver will be permanently broken.

Marionette and geckodriver means to replace FirefoxDriver as a vendor-supported WebDriver implementation by Mozilla. Marionette is built in to Firefox, which gives it greater capabilities than FirefoxDriver had, but at the same time means it is bound to the Firefox release it ships in.

At the same time as we are implementing WebDriver, we are simultaneously aligning it with the forthcoming [W3C WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html), and some of the breakage you see stems from Selenium (in this case), geckodriver, Marionette, or a combination of some or all of them being out of sync. This is unfortunate, but we are making great strides in compatibility between the different moving parts.

We want users to be able to pick up any recent version of Firefox and use it with WebDriver, but we are limited by such inconveniences as real life and the fact that once you ship native software, it’s not easy to update it.

I’m truly sorry for the instability users are experiencing with geckodriver, but we are making a conscious effort to resolve the highest priority issues that are reported in a timely manner.

**Comment by nkrishnanChrome** [comment]
I am facing the same issue. Please let me know which version can i degrade Firefox browser , gecko driver and selenium to make it work again

**Comment by pbi-qfs** [comment]
F52 + Selenium 3..3.1 + Geckodriver 0.15 do not throw an exception (at least). I'm quite aunsure if any version of geckodriver supported setPosition before 0.16...

Selenium problem is fixed with [SeleniumHQ/selenium#6c6e7ca](https://github.com/SeleniumHQ/selenium/commit/6c6e7cab9075103f2131e410facd6affe6d779bd)

**Comment by BrandonDude** [comment]
Still an issue with:

**Selenium:** 3.4
**Geckodriver:** 0.17.0
**Firefox:** 54.0 (64-bit)
**Windows:** 7

This has also been reported in issues [403](https://github.com/mozilla/geckodriver/issues/403) & [676](https://github.com/mozilla/geckodriver/issues/676).

**Comment by pbi-qfs** [comment]
You'll have to wait for Selenium 3.4.1 (since it's a Selenium binding problem) or build selenium yourself from sources

**Comment by BrandonDude** [comment]
https://github.com/SeleniumHQ/selenium/issues/3995
