### ISSUE TITLE
Calling maximize_window causes script to hang

### ISSUE THREAD

**Issue by davehunt** [mozilla/geckodriver#703]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
55.0a1 (2017-04-28) (64-bit)

## Platform
macOS 10.12.4

## Other
geckodriver 0.16.1
selenium 3.4.1 (Python)

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [X] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

No HTML necessary to reproduce bug.

 - [X] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

```
1493398038115	geckodriver	INFO	Listening on 127.0.0.1:65472
1493398039262	geckodriver::marionette	INFO	Starting browser /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1493398039265	geckodriver::marionette	TRACE	  connection attempt 0/600
1493398039370	geckodriver::marionette	TRACE	  connection attempt 1/600
1493398039474	geckodriver::marionette	TRACE	  connection attempt 2/600
1493398039575	geckodriver::marionette	TRACE	  connection attempt 3/600
1493398039677	geckodriver::marionette	TRACE	  connection attempt 4/600
1493398039779	geckodriver::marionette	TRACE	  connection attempt 5/600
1493398039883	geckodriver::marionette	TRACE	  connection attempt 6/600
1493398039988	geckodriver::marionette	TRACE	  connection attempt 7/600
1493398040092	geckodriver::marionette	TRACE	  connection attempt 8/600
1493398040199	geckodriver::marionette	TRACE	  connection attempt 9/600
1493398040300	geckodriver::marionette	TRACE	  connection attempt 10/600
1493398040408	geckodriver::marionette	TRACE	  connection attempt 11/600
1493398040511	geckodriver::marionette	TRACE	  connection attempt 12/600
1493398040617	geckodriver::marionette	TRACE	  connection attempt 13/600
1493398040726	geckodriver::marionette	TRACE	  connection attempt 14/600
1493398040829	geckodriver::marionette	TRACE	  connection attempt 15/600
1493398040934	geckodriver::marionette	TRACE	  connection attempt 16/600
1493398041042	geckodriver::marionette	TRACE	  connection attempt 17/600
1493398041146	geckodriver::marionette	TRACE	  connection attempt 18/600
1493398041258	geckodriver::marionette	TRACE	  connection attempt 19/600
1493398041362	geckodriver::marionette	TRACE	  connection attempt 20/600
1493398041477	geckodriver::marionette	TRACE	  connection attempt 21/600
1493398041587	geckodriver::marionette	TRACE	  connection attempt 22/600
2017-04-28 17:47:21.648 plugin-container[36041:20355739] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa32b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-28 17:47:21.651 plugin-container[36041:20355739] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa703, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1493398041699	geckodriver::marionette	TRACE	  connection attempt 23/600
1493398041812	geckodriver::marionette	TRACE	  connection attempt 24/600
1493398041917	geckodriver::marionette	TRACE	  connection attempt 25/600
1493398041957	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1493398041957	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1493398041957	Marionette	INFO	Listening on port 65485
1493398042020	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:65485
1493398042057	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49186
1493398042076	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
1493398042076	geckodriver::marionette	TRACE	→ 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1493398042094	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1493398042104	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":36040,"moz:profile":"/var/folders/3y/wrsgzz095jb2dg7vk9wnd42r0000gn/T/rust_mozprofile.4UflLjm2E8Bf","moz:accessibilityChecks":false}
1493398042104	Marionette	WARN	TLS certificate errors will be ignored for this session
1493398042152	Marionette	DEBUG	loaded listener.js
1493398042163	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"9cab90fa-c62f-6947-af5f-1e40506ec751","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":36040,"moz:profile":"/var/folders/3y/wrsgzz095jb2dg7vk9wnd42r0000gn/T/rust_mozprofile.4UflLjm2E8Bf","moz:accessibilityChecks":false}}]
1493398042164	geckodriver::marionette	TRACE	← [1,1,null,{"sessionId":"9cab90fa-c62f-6947-af5f-1e40506ec751","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"darwin","platformVersion":"16.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":36040,"moz:profile":"/var/folders/3y/wrsgzz095jb2dg7vk9wnd42r0000gn/T/rust_mozprofile.4UflLjm2E8Bf","moz:accessibilityChecks":false}}]
1493398042164	webdriver::server	DEBUG	← 200 OK {"value": {"sessionId":"9cab90fa-c62f-6947-af5f-1e40506ec751","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":36040,"moz:profile":"/var/folders/3y/wrsgzz095jb2dg7vk9wnd42r0000gn/T/rust_mozprofile.4UflLjm2E8Bf","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1493398042167	webdriver::server	DEBUG	→ POST /session/9cab90fa-c62f-6947-af5f-1e40506ec751/window/maximize {"windowHandle": "current", "sessionId": "9cab90fa-c62f-6947-af5f-1e40506ec751"}
1493398042168	geckodriver::marionette	TRACE	→ 25:[0,2,"maximizeWindow",{}]
1493398042171	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
```

The following script causes a hang until the window is manually resized:

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

o = Options()
o.log.level = 'trace'
o.binary = '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin'

f = Firefox(firefox_options=o)
f.maximize_window()
assert True
```

After manually resizing the window, the script continues and the following additional lines are written to the log file:

```
1493398075972	Marionette	TRACE	0 <- [1,2,null,{"x":-1657,"y":-791,"width":1288,"height":777}]
1493398075973	geckodriver::marionette	TRACE	← [1,2,null,{"x":-1657,"y":-791,"width":1288,"height":777}]
1493398075973	webdriver::server	DEBUG	← 200 OK {"value": {}}
1493398076027	Marionette	DEBUG	Closed connection 0
```

Note that the window is already maximized when `maximize_window` is called. If I add a sleep and reduce the window size, the script completes as expected. I'm also using two screens, and moving the window to the second screen (where it is no longer taking up the full height/width) before called `maximize_window` the script still fails as described.

**Comment by jeanpylone** [comment]
Hello,

I have the same problem with Firefox 53.0, geckodriver 0.16.1 and selenium 3.4.0, either on Windows 10 or on Linux Mint.
I use browser.driver.manage().window().setSize() for my tests. Doing some tests with with wireshark, I saw that setSize works the first time (sending POST /wd/hub/session/xxx/window/current/size and POST /session/xxx/window/rect at the same time), and indeed the browser size changes. But in a second test I do a setSize with the exact same size and here all the following requests never get answer (including POST /wd/hub/session/xxx/window/current/size and POST /session/xxx/window/rect).

**Comment by andreastt** [comment]
I suspect that this was fixed as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1357878, which is available in Firefox 55 or greater. It would be great if someone could try that out and confirm it works!

**Comment by andreastt** [comment]
@jeanpylone Setting the window’s _size_ is fundamentally different to maximising: they are two separate endpoints and commands.

We had an issue recently where calling Set Window Rect/`setSize` twice with the same arguments caused Marionette to never return a response, see https://github.com/mozilla/geckodriver/issues/643. That particular problem was also patched in https://bugzilla.mozilla.org/show_bug.cgi?id=1357878.

**Comment by davehunt** [comment]
@andreastt I am still seeing this with 55.0a1 (2017-05-03) (64-bit)

**Comment by andreastt** [comment]
@davehunt That is odd.

What I see locally when the window isn’t maximized:

```
>>> m.maximize_window()
1493894089253	Marionette	TRACE	2 -> [0,3,"maximizeWindow",{}]
1493894089317	Marionette	TRACE	2 <- [1,3,null,{"x":0,"y":0,"width":1912,"height":1072}]
{u'y': 0, u'x': 0, u'height': 1072, u'width': 1912}
>>> m.maximize_window()
1493894098990	Marionette	TRACE	2 -> [0,4,"maximizeWindow",{}]
1493894099034	Marionette	TRACE	2 <- [1,4,null,{"x":24,"y":48,"width":1280,"height":972}]
{u'y': 48, u'x': 24, u'height': 972, u'width': 1280}
```

When I maximize the window manually first, then call `m.maximize_window`, it hangs as you described.

The implementation of Maximize Window looks like this:

```js
  yield new Promise(resolve => {
    win.addEventListener("resize", resolve, {once: true});

    if (win.windowState == win.STATE_MAXIMIZED) {
      win.restore();
    } else {
      win.maximize();
    }
  });
```

That means that `win.windowState` isn’t being set to the `win.STATE_MAXIMIZED` when the window is manually made to fit the full window. My guess is that `win.restore`/`win.maximize` contains a check to _not_ run the operation if the window dimensions match the destination, and that this is why the promise is failing.

**Comment by andreastt** [comment]
On further investigation, when the window is manually resized to fit the screen, the code above is supposed to restore the window to its former size. Its former size is the size of the screen, and the window state consequently reports it as maximized. This is why the promise fails to resolve.

**Comment by whimboo** [comment]
So what happens if the window has the size of the screen when not being maximized, and then you do a `maximize()`? The dimensions shouldn't change, right? So no `resize` event should be send.

**Comment by andreastt** [comment]
Yes, I would expect that to trigger the same behaviour because
`window.maximize` tests if it needs to do anything (e.g. is the window
the desired size already, if so, bail out), which will cause `resize` to
never fire.

**Comment by FelipeJK** [comment]
Hi all,
I am getting "org.openqa.selenium.WebDriverException: getWindowRect" just calling driver..manage().window().getSize();..

Does someone else also get this issue?

Some log info:
494620707802	webdriver::server	DEBUG	â†’ GET /session/cce999bf-940d-48bd-b4a5-b5f5e2e7a45c/window/rect 
1494620707802	geckodriver::marionette	TRACE	â†’ 27:[0,1300,"getWindowRect",{}]
1494620707804	Marionette	TRACE	conn0 -> [0,1300,"getWindowRect",{}]
1494620707804	Marionette	TRACE	conn0 <- [1,1300,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494620707805	geckodriver::marionette	TRACE	â†? [1,1300,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494620707806	webdriver::server	DEBUG	â†? 404 Not Found {"value":{"error":"unknown error","message":"getWindowRect","stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x43a15d - <no info>\n   3:           0x4474c9 - <no info>\n   4:           0x445208 - <no info>\n   5:           0x41ddb1 - <no info>\n   6:           0x4091c7 - <no info>\n   7:           0x6bc939 - <no info>\n   8:           0x415a19 - <no info>\n   9:           0x6b6e43 - <no info>\n  10:     0x7ffb90128364 - BaseThreadInitThunk"}}
mai 12, 2017 5:25:07 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]


Thanks

**Comment by andreastt** [comment]
@FelipeJK Which Firefox version are you using? Your error isn’t related to this issue, as you can see from your stacktrace. It is complaining about the the fact that the `getWindowRect` command doesn’t exist in the Marionette server, so I’m guessing your Firefox version is pretty old?

**Comment by FelipeJK** [comment]
@andreastt I am using official Firefox 52 ESR, build 52.1.1.

**Comment by andreastt** [comment]
@FelipeJK According to https://bugzilla.mozilla.org/show_bug.cgi?id=1347589, the Marionette `setWindowRect` command is only available in Firefox 53 or greater. Sorry for this.

**Comment by andreastt** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1375185 to fix this in Marionette.

**Comment by wjsffzb** [comment]
操作系统：win10

**Comment by whimboo** [comment]
@davehunt do you still see this problem with latest Nightly?

**Comment by davehunt** [comment]
I can no longer replicate this with latest geckodriver and Firefox Nightly.
