### ISSUE TITLE
DOM events focus, change, and blur are not generated if multiple browsers run in parallel (stealing focus)

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#906]
## System
* Version: 0.18
* Platform: windows 7
* Firefox: Nightly 57.0a1 (2017-08-28) (64-bit)
* Selenium: 3.5.2 Java

## Testcase
```
WebDriver driver = new FirefoxDriver();
WebDriver driver2 = new FirefoxDriver();
driver.get("https://output.jsbin.com/toxabibuke");
driver2.get("https://output.jsbin.com/toxabibuke");
driver.findElement(By.id("plainButton")).click();
driver2.findElement(By.id("plainButton")).click();
// this check passes because it's topmost window
assertEquals(driver2.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
// but this check fails
assertEquals(driver.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
```

**Comment by barancev** [comment]
Similar issue with blur:
```
driver.get("https://output.jsbin.com/toxabibuke");
driver2.get("https://output.jsbin.com/toxabibuke");
driver.findElement(By.id("textField")).sendKeys("x" + Keys.TAB);
driver2.findElement(By.id("textField")).sendKeys("x" + Keys.TAB);
// this check passes because it's topmost window
assertEquals(driver2.findElement(By.id("resultParagraph")).getText().trim(), "focus keydown keypress keyup keydown keypress blur");
// but this check fails
assertEquals(driver.findElement(By.id("resultParagraph")).getText().trim(), "focus keydown keypress keyup keydown keypress blur");
```

**Comment by andreastt** [comment]
Probably testing/marionette/event.js and/or nsIWindowUtils is not taking lack of focus into account. I thought this would be solved by disabling the focus manager through the pref. More investigation needed.

**Comment by whimboo** [comment]
Just to be sure because it's not clear from the above, `driver` and `driver2` are using completely different instances of geckodriver and Firefox?

**Comment by barancev** [comment]
@whimboo Yes, like it's shown in the first example.

**Comment by whimboo** [comment]
That's not that clear given that geckodriver starts at the same port and it would mean that you are using the same instance twice, which ends up with the same Firefox instance too. But thanks for the clarification.

**Comment by whimboo** [comment]
Btw. is the same also visible when running Firefox in headless mode?

**Comment by barancev** [comment]
Sorry, the page was created in non-authenticated session and expired, here is the persistent page for the samples: https://output.jsbin.com/remozek/1

**Comment by barancev** [comment]
In headless mode both browsers work well, no issues.

**Comment by whimboo** [comment]
Let me just ask something more... So by default geckodriver launches Firefox in the background, and I haven't seen issues with `click` not working in that mode. Can you verify that your issue is only persistent when Firefox is in background and multiple instances are running?

**Comment by barancev** [comment]
For me, it starts new browsers in foreground. If I stop in debugger and put both browsers to background scenario fails on the fist assert (because the browser is not topmost).

May it be a Windows specific isue?

**Comment by whimboo** [comment]
Maybe. Personally I haven't seen issues with click myself yet if Firefox is in background. 

Could you please try to get it recreated with a single instance of Firefox only? Both processes shouldn't interfere with each other but just to be sure, and to help us investigating the issue. Thanks.

**Comment by barancev** [comment]
Yes, I can reproduce it with a single browser if I stop it in debugger before click and put to background.

**Comment by whimboo** [comment]
@barancev, the test as given doesn't work. I had a quick look but the elements you are referring to here, are located in iframes which means the test would need at least to calls to `switch_to_frame()`. Can you please provide a testcase which will definitely work? Thanks.

**Comment by barancev** [comment]
```
WebDriver driver = new FirefoxDriver();
WebDriver driver2 = new FirefoxDriver();
driver.get("https://output.jsbin.com/remozek/1");
driver2.get("https://output.jsbin.com/remozek/1");
driver.findElement(By.id("plainButton")).click();
driver2.findElement(By.id("plainButton")).click();
// this check passes because it's topmost window
assertEquals(driver2.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
// but this check fails
assertEquals(driver.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
```

**Comment by whimboo** [comment]
Ok, so that's better but I think your assumption to get a focus is not correct. It doesn't matter if Firefox is in foreground or background, clicking the button always creates three events for me which are: `mousedown mouseup click`. And that even when I try manually.

So I will take the follow test for the Python bindings into account, which perfectly reproduces it for me:

```
    def test_failure_running_in_background(self):
        self.driver.get("https://output.jsbin.com/remozek/1")
        self.driver.find_element_by_id("textField").send_keys("x" + Keys.TAB)

        result = self.driver.find_element_by_id("resultParagraph")
        self.assertEqual(result.text.strip(),
                         "focus keydown keypress keyup keydown keypress blur")
```

**Comment by whimboo** [comment]
It's very interesting. When I run the same test directly with Marionette it doesn't matter if Firefox is in foreground or background. The `focus` event is always recorded. So there is something special geckodriver is doing here to get Firefox started, or a preference which I wasn't able to figure out yet.

I will have a look into that.

**Comment by whimboo** [comment]
I tried to figure what's wrong but haven't been lucky yet. So I filed [bug 1398111](https://bugzilla.mozilla.org/show_bug.cgi?id=1398111) for the time being.

Thank you for reporting @barancev!

**Comment by kmaterka** [comment]
I think it is not geckodriver issue, we had similar issues. It is described here:
https://makandracards.com/makandra/12661-how-to-solve-selenium-focus-issues
To summarize: clicking on a text field will only trigger a focus and blur events when Firefox window is currently in focus.

**Comment by HouCoder** [comment]
I had the same issue, I was using WebDriver.IO, here is my temporary workaround:


**In your config**

```js
before() {
    const currentBrowserName = browser.desiredCapabilities.browserName.toLowerCase();

    browser.isFirefox = currentBrowserName === 'firefox';
}

```

**In your testing script**

```js
if (browser.isFirefox) {
    browser.execute(() => {
        // Trigger blur event manually.
        $('#user-search').blur();
    }, this.searchInputBox);
}
```

**Comment by andreastt** [comment]
https://github.com/mozilla/geckodriver/issues/1131 was filed about text input, so this isn’t specific to clicking.

**Comment by Lucasgermani** [comment]
Any update regarding this issue? 
It's been months that is open

**Comment by andreastt** [comment]
[Bug 1398111](https://bugzilla.mozilla.org/show_bug.cgi?id=1398111) is on the backlog, so is not prioritised this quarter.

**Comment by whimboo** [comment]
@Lucasgermani if you want to see it working just add the `-foreground` option to the Firefox args. Then Firefox will not run in background as done by default with geckodriver.

**Comment by Kenith** [comment]
same issue here

**Comment by rahulkaringat** [comment]
Click failed on the key: [[FirefoxDriver: firefox on XP (d84bb01a-0c4d-479c-90c1-a4210c75c8d9)] -> xpath: //h6[contains(text(),'Revenue')]]
Hi anybody know what is this one.i am getting same problem with different xpath

**Comment by whimboo** [comment]
This was actually an issue with Marionette and should have been fixed with my patch on [bug 1398111](https://bugzilla.mozilla.org/show_bug.cgi?id=1398111).

@barancev can you please retry with a recent Nightly or beta of Firefox? Thanks.

**Comment by barancev** [comment]
The issue is still actual in the Nightly 64.0a1 (2018-09-10) (64-bit), here is the updated scenario:
```
    @Test
    public void test1() {
        WebDriver driver = new FirefoxDriver(new FirefoxOptions().setBinary(new FirefoxBinary(FirefoxBinary.Channel.NIGHTLY)));
        WebDriver driver2 = new FirefoxDriver(new FirefoxOptions().setBinary(new FirefoxBinary(FirefoxBinary.Channel.NIGHTLY)));
        driver.get("https://output.jsbin.com/nusuy");
        driver2.get("https://output.jsbin.com/nusuy");
        driver.findElement(By.id("plainButton")).click();
        driver2.findElement(By.id("plainButton")).click();
        // this check passes because it's topmost window
        assertEquals(driver2.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
        // but this check fails
        assertEquals(driver.findElement(By.id("resultParagraph")).getText().trim(), "mousedown focus mouseup click");
    }
```

**Comment by whimboo** [comment]
So the above example doesn't even work for me when Firefox is the top-most application, and I can see why this is the case. So how does it work for you? @barancev, can you show me a  trace log please? I'm fairly sure this has nothing to do with the focus.

Please also check the following example, which should clearly show the focus, and blur event when Firefox is running in background:
```
        driver.get("https://output.jsbin.com/remozek/1")
        input = driver.find_element_by_id("textField")
        input.send_keys("x" + Keys.TAB)

        result = driver.find_element_by_id("resultParagraph")
        assert result.text.strip() == "focus keydown keypress keyup keydown blur"
```

**Comment by barancev** [comment]
@whimboo Yes, your example works well. But if I modify it to start a second browser that grabs the focus -- it fails:
```
        driver.get("https://output.jsbin.com/remozek/1");
        WebDriver driver2 = new FirefoxDriver(
                new FirefoxOptions().setBinary(new FirefoxBinary(FirefoxBinary.Channel.NIGHTLY)));
        WebElement input = driver.findElement(By.id("textField"));
        input.sendKeys("x" + Keys.TAB);

        WebElement result = driver.findElement(By.id("resultParagraph"));
        assertEquals(result.getText().trim(), "focus keydown keypress keyup keydown blur");
```

**Comment by whimboo** [comment]
Yes, this is most likely due to https://bugzilla.mozilla.org/show_bug.cgi?id=1489967 I'm working on right now.

Ok, so we should limit this issue to `Element Click` and the `focus` event. @barancev do you agree with that?

**Comment by barancev** [comment]
`sendKeys` does not work too, as I shown in the previos example.

**Comment by barancev** [comment]
I can reproduce it with a single browser window if I set a breakpoint in debugger and manually activate some other window to take focus out of the browser window.

**Comment by barancev** [comment]
There are two cases:
1) browser sometimes does not grab focus on start (repored as https://bugzilla.mozilla.org/show_bug.cgi?id=1488213)
2) browser does not fire focus and blur events if it runs in background (the current issue)

**Comment by whimboo** [comment]
I just asked @barancev to run a developer build of Firefox with my fix on https://bugzilla.mozilla.org/show_bug.cgi?id=1489967 included. As he told me it fixes all the remaining issues! Thanks!

I expect the fix to be landed soon, and I will request uplift for Firefox 63 beta too.

**Comment by whimboo** [comment]
This is fixed in the latest Firefox Nightly now.
