### ISSUE TITLE
Take Screenshot should capture top-level browser context, not current context

### ISSUE THREAD

**Issue by juangj** [mozilla/geckodriver#936]
## System
* Version: 0.18.0
* Platform: Linux
* Firefox: 55.0
* Selenium: Java 3.4.0, I think, but it doesn't matter

### `iframe_page.html`

```html
<div style="border:1px solid blue">
  <div>Outer frame</div>
  <iframe id="f" srcdoc="<span style='border:1px solid red'>Inner frame</span>"></iframe>
</div>
```

### `iframe_page.py`

```py
import sys

from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Remote(command_executor=sys.argv[1],
                          desired_capabilities=DesiredCapabilities.FIREFOX.copy())

driver.get('http://localhost/iframe_page.html')
driver.switch_to.frame('f')
driver.get_screenshot_as_file('/tmp/s.png')
driver.quit()
```

### Description

https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot says it "takes a screenshot of the top-level browsing context’s viewport".

The screenshot produced by the test contains just the inner frame. It should also include the outer frame.

## Trace-level log

[geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1286113/geckodriver.log.txt)

**Comment by AutomatedTester** [comment]
raised https://bugzilla.mozilla.org/show_bug.cgi?id=1398087

**Comment by whimboo** [comment]
This issue has been fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1385706 for Firefox 66.

**Comment by zeit200** [comment]
@whimboo, hi, am I mistaken or https://bugzilla.mozilla.org/show_bug.cgi?id=1385706 fixes screenshots size of the currently selected frame and does not fix the issue described here?
Tried on Firefox 66.0b4 and it still produces screenshots of the currently selected frame instead of the top-level browsing context’s viewport.

**Comment by whimboo** [comment]
@andreastt can you please revisit given that you worked with the contributor on that fix? Thanks.

**Comment by andreastt** [comment]
https://github.com/mozilla/geckodriver/issues/936#issuecomment-454801635 incorrectly assumed https://bugzilla.mozilla.org/show_bug.cgi?id=1385706 fixes this problem. Re-opening.

**Comment by andreastt** [comment]
I’ve corrected the mistake of duplicating https://bugzilla.mozilla.org/show_bug.cgi?id=1398087, which tracks this problem on the Marionette side.

**Comment by zeit200** [comment]
thanks!

**Comment by whimboo** [comment]
This got actually fixed in Firefox 70. I will re-use https://bugzilla.mozilla.org/show_bug.cgi?id=1398087 to get a Webdriver test written.

**Comment by whimboo** [comment]
While we take a screenshot of the top level browsing context now, we still grab the dimensions from the frame itself. I will have to push a follow-up fix, which I would like to see landed for Firefox 73.

**Comment by whimboo** [comment]
The fix landed via the above mentioned bug, and is available in today's Nightly build now.

**Comment by QA-Rahul** [comment]
It does not take full screenshot of iframe. I mean if iframe has long content with scroll bar, it does not take full screenshot. Any input?

**Comment by whimboo** [comment]
@QA-Rahul, your comment doesn't belong to this issue. Instead it is not possible yet due to restrictions of the WebDriver specification: https://w3c.github.io/webdriver/#take-screenshot.

Feel free to file a new WebDriver spec issue about allowing `Take Screenshot` also for any browsing context and not only the parent one. But even then full screenshots aren't covered by the spec yet.
